# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-12 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeelist', '0003_auto_20180730_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coffeelist.Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date when the price changed'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of purchase'),
        ),
    ]
