# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeelist', '0004_auto_20180812_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='price',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='date',
        ),
    ]
