# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-13 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coffeelist', '0005_auto_20180813_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of transaction'),
        ),
        migrations.AddField(
            model_name='price',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date when the price changed'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of purchase'),
        ),
    ]
