# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coffeelist', '0006_auto_20180813_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coffeelist.Price'),
        ),
    ]
